[workspace]
authors = ["longred <longredzhong@outlook.com>"]
channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]
name = "bungee-python"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
version = "0.1.0"

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
extra-index-urls = ["https://pypi.mirrors.ustc.edu.cn/simple", "https://pypi.python.org/simple"]

[tasks]

[dependencies]
python = ">=3.8"
numpy = "*"

cmake = "*"
ninja = ">=1.12.1,<2"
cxx-compiler = "*"
pip = "*"
pytest = ">=8.3.5,<9"
pytest-cov = ">=6.1.1,<7"

[pypi-dependencies]
bungee-python = { path = "."}

[package]
name = "bungee-python"
version = "0.1.1"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies] 
scikit-build-core = ">=0.7"

[package.run-dependencies] 
numpy = "*"