import numpy as np
from numpy.typing import NDArray

class Bungee:
    def __init__(self, sample_rate: int, channels: int) -> None: ...
    @property
    def speed(self) -> float: ...
    @speed.setter
    def speed(self, value: float) -> None: ...
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    @property
    def instrumentation(self) -> bool: ...
    @instrumentation.setter
    def instrumentation(self, value: bool) -> None: ...
    def set_speed(self, speed: float) -> None: ...
    def set_pitch(self, pitch: float) -> None: ...
    def process(self, input: NDArray[np.float32]) -> NDArray[np.float32]: ...
